# -*- coding: utf-8 -*-
"""02_Finding the percentage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s917tSnOEZ5qH1tz2iubg_uTwnOzQF9f

# Finding the percentage

### This Python code calculates the average of scores for a given student. The program takes input for the number of students, their names, and corresponding scores. Then, it takes a query name and prints the average scores for that student.

##Method 01
"""

if __name__ == '__main__':

    n = int(input())   # Input the number of students

    student_marks = {}  # Dictionary to store student names and their scores

    # Input loop to get student names and scores
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores

    # Input the name for which average scores are to be calculated
    query_name = input()

    # Retrieve the scores for the queried student
    query_scores = student_marks[query_name]

    # Calculate and print the average scores
    avg = sum(query_scores) / len(query_scores)
    print("%.2f" % avg)

"""##Method 02"""

if __name__ == '__main__':
    # Input the number of students
    num_students = int(input("Enter the number of students: "))

    # Dictionary to store student names and their scores
    student_marks = {}

    # Input loop to get student names and scores
    for i in range(num_students):
        student_name = input("Enter name of Student {}: ".format(i+1))
        scores = [float(input("Enter score for Subject {}: ".format(j+1))) for j in range(3)]
        student_marks[student_name] = scores

    # Input the query name
    query_name = input("Enter the query name: ")

    # Retrieve the scores for the queried student
    query_scores = student_marks.get(query_name, [])

    if query_scores:
        # Calculate and print the average scores
        avg = sum(query_scores) / len(query_scores)
        print("Average score for {}: {:.2f}".format(query_name, avg))
    else:
        print("Student not found.")